# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Interactibook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Database'
  # Pods for Interactibook

  target 'InteractibookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InteractibookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
